### ISSUE TITLE
math.pi is a float, causes error when inputting Decimal points

### ISSUE THREAD

**Issue by Grantward1** [seangrogan/great_circle_calculator#3]
In _constants.py, pi is set as math.pi, which is a float. This should be a Decimal since it causes a type error when using functions like distance_between_points on Decimal points.

You can temporarily fix this by doing
`import decimal`
`from great_circle_calculator import _constants`
`_constants.pi = decimal.Decimal(_constants.pi)`
`import great_circle_calculator.great_circle_calculator as gcc`

**Comment by seangrogan** [comment]
I spent some time trying to come up with an easy way of switching between decimal and float.  For the time being, it converts everything to floats.  If you have any ideas or suggestions for a more elegant switch between the two, I'm all ears

**Comment by Grantward1** [comment]
Ok my confusion comes from reading the docs on PYPI which say 'decimal degrees' so I was assuming the functions all required Decimal inputs.

As for your problem switching between the two, maybe you could set the constant values to instead be functions that return either `Decimal(constant_value)` or `float(constant_value)` depending on a setting that can be changed via `gcc.set_decimal_class(new_class)` or something. So it would default to float but you could change it to Decimal for all subsequent operations.

**Comment by seangrogan** [comment]
Ahh no, I see the confusion.  Decimal degrees vs Degree-Minute-Second, I wanted to make sure the user didn't use something like 40° 45' 35", -73° 58' 30" instead of 40.75984, -73.9751.  

I did entertain the idea of using the Decimal datatype in development but abandoned it because 1) most of the geospatial data I'm using (And I'm aware of) is in float data types 2) the precision and/or accuracy that decimal provides is usually unnecessarily precise  at earth scales.  

I'll update the Readme for more clarity.
